"A2A.MI": "A2A S.p.A."
"ATL.MI": "Atlantia S.p.A."
"AZM.MI": "Azimut Holding S.p.A."
"BGN.MI": "Banca Generali S.p.A."
"BMED.MI": "Banca Mediolanum S.p.A."
"BAMI.MI": "Banco BPM S.p.A"
"BPE.MI": "BPER Banca S.p.A."
"BRE.MI": "Brembo S.p.A."
"BZU.MI": "Buzzi Unicem S.p.A."
"CPR.MI": "Campari - Milano S.p.A."
"CNHI.MI": "CNH Industrial N.V."
"ENEL.MI": "Enel S.p.A."
"ENI.MI": "Eni S.p.A."
"EXO.MI": "Exor N.V."
"RACE.MI": "Ferrari N.V."
"FCA.MI": "Fiat Chrysler Automobiles N.V."
"FBK.MI": "FinecoBank S.p.A."
"G.MI": "Generali S.p.A."
"ISP.MI": "Intesa Sanpaolo S.p.A."
"IG.MI": "Italgas S.p.A."
"LDO.MI": "Leonardo S.p.A."
"LUX.MI": "Luxottica S.p.A."
"MS.MI": "Mediaset S.p.A."
"MB.MI": "Mediobanca S.p.A."
"MONC.MI": "Moncler S.p.A."
"PIRC.MI": "Pirelli & C. S.p.A.[11]"
"PST.MI": "Poste italiane S.p.A."
"PRY.MI": "Prysmian S.p.A."
"REC.MI": "Recordati S.p.A."
"SPM.MI": "Saipem S.p.A."
"SFER.MI": "Salvatore Ferragamo S.p.A."
"SRG.MI": "Snam S.p.A."
"STM.MI": "STMicroelectronics N.V."
"TIT.MI": "Telecom Italia S.p.A."
"TEN.MI": "Tenaris S.A."
"TRN.MI": "Terna - Rete Elettrica Nazionale S.p.A."
"UBI.MI": "UBI Banca S.p.A."
"UCG.MI": "UniCredit S.p.A.[12]"
"UNI.MI": "Unipol S.p.A."
"US.MI": "UnipolSai Assicurazioni S.p.A."
